Document: goes-boot-mk1
Title: Debian goes-boot-mk1 Manual
Author: <insert document author here>
Abstract: This manual describes what goes-boot-mk1 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/goes-boot-mk1/goes-boot-mk1.sgml.gz

Format: postscript
Files: /usr/share/doc/goes-boot-mk1/goes-boot-mk1.ps.gz

Format: text
Files: /usr/share/doc/goes-boot-mk1/goes-boot-mk1.text.gz

Format: HTML
Index: /usr/share/doc/goes-boot-mk1/html/index.html
Files: /usr/share/doc/goes-boot-mk1/html/*.html
